### ISSUE TITLE
CLI: Debug Information in SPIR-V output

### ISSUE THREAD

**Issue by namandixit** [libsdl-org/SDL_shadercross#64]
Will it be possible to add a flag to output the SPIR-V code with debug information (`dxc.exe`'s equivalent of `-fspv-debug=vulkan-with-source`)? This would allow [debugging shaders using RenderDoc](https://renderdoc.org/docs/how/how_debug_shader.html).

**Comment by thatcosmonaut** [comment]
It's possible. PRs welcome!

**Comment by thatcosmonaut** [comment]
Yes but you should only add it if the target is SPIR-V. There is a different flag for DXIL debugging.

**Comment by madebr** [comment]
That command looks fine.
I think Microsoft's DirectXShaderCompiler does not support `-DBUILD_SHARED_LIBS=ON`.
Can you try the following patch?
```diff
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -120,6 +120,7 @@ if(SDLSHADERCROSS_VENDORED)
        add_library(DirectXShaderCompiler::dxcompiler ALIAS dxcompiler)
        add_library(DirectXShaderCompiler::dxil ALIAS dxildll)
        list(APPEND vendored_targets dxcompiler dxildll)
+       set(BUILD_SHARED_LIBS OFF)
        add_dependencies(dxcompiler dxildll)
 
        export(TARGETS ${vendored_targets} NAMESPACE "SDL3_shadercross::" FILE "SDL3_shadercross-vendored-targets.cmake")
```
