### ISSUE TITLE
Compiler warnings can't be disabled and are fatal

### ISSUE THREAD

**Issue by jclc** [libsdl-org/SDL_shadercross#70]
I'm trying to compile a shader which includes [FastNoiseLite](https://github.com/Auburn/FastNoiseLite) and I'm getting this:

```
ERROR: Failed to compile SPIR-V From HLSL: HLSL compilation failed: In file included from hlsl.hlsl:1:
./FastNoiseLite.hlsl:1654:27: warning: overflow in expression; result is -2021106534 with type 'int' [-Winteger-overflow]
    int y3 = y1 + PRIME_Y * 2;
                          ^
./FastNoiseLite.hlsl:1689:27: warning: overflow in expression; result is -2021106534 with type 'int' [-Winteger-overflow]
    int y3 = y1 + PRIME_Y * 2;
                          ^
./FastNoiseLite.hlsl:1690:27: warning: overflow in expression; result is -854139810 with type 'int' [-Winteger-overflow]
    int z3 = z1 + PRIME_Z * 2;
                          ^
```

I'm pretty sure the overflow is intentional. Is there a way to disable compiler warnings or at least make them non-fatal?

**Comment by thatcosmonaut** [comment]
Oh, I guess DXC returns warnings in the error blob. We can fix this.

**Comment by jclc** [comment]
On a related note, would it be possible to pass options to DXC?

**Comment by thatcosmonaut** [comment]
Maybe but that opens up a big can of worms. What's the use case?

**Comment by jclc** [comment]
Just to disable these warnings

**Comment by jclc** [comment]
Well, I suppose suppressing warnings can be just done on the SDL_shadercross side more easily, if there's no other reason to pass options

**Comment by jclc** [comment]
Looks like the proper way to ignore individual warnings is to add a pragma statement before the offending expression:
```
#pragma dxc diagnostic ignored "-Winteger-overflow"
```

**Comment by thatcosmonaut** [comment]
@jclc Could you test this patch and see if it resolves this issue: https://github.com/libsdl-org/SDL_shadercross/pull/74

**Comment by jclc** [comment]
Works great!
